// packages/vue/src/SciFlow.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useSciFlow } from './useSciFlow';
import type { UseSciFlowProps } from './useSciFlow';
import type { Node } from '@sci-flow/core';
import type { Component } from 'vue';

// Props typed correctly — nodeTypes is a Record for Vue (component-by-name)
const props = defineProps<{
    initialNodes?: UseSciFlowProps['initialNodes'];
    initialEdges?: UseSciFlowProps['initialEdges'];
    renderer?: UseSciFlowProps['renderer'];
    theme?: UseSciFlowProps['theme'];
    direction?: UseSciFlowProps['direction'];
    minZoom?: UseSciFlowProps['minZoom'];
    maxZoom?: UseSciFlowProps['maxZoom'];
    onNodeContextMenu?: UseSciFlowProps['onNodeContextMenu'];
    onEdgeContextMenu?: UseSciFlowProps['onEdgeContextMenu'];
    onPaneContextMenu?: UseSciFlowProps['onPaneContextMenu'];
    onInit?: (engine: InstanceType<typeof import('@sci-flow/core').SciFlow>) => void;
    // Vue components mapped by node type name
    nodeTypes?: Record<string, Component>;
}>();

const { containerRef, portalMounts, nodes, engine, highlightedConnection } = useSciFlow({
    initialNodes: props.initialNodes,
    initialEdges: props.initialEdges,
    renderer: props.renderer,
    theme: props.theme,
    direction: props.direction,
    minZoom: props.minZoom,
    maxZoom: props.maxZoom,
    onNodeContextMenu: props.onNodeContextMenu,
    onEdgeContextMenu: props.onEdgeContextMenu,
    onPaneContextMenu: props.onPaneContextMenu,
    onInit: props.onInit,
});

// Derive mount list — only include entries with a registered component
const mountsArray = computed(() => {
    return Array.from(portalMounts.value.entries())
        .map(([nodeId, domElement]) => {
            const nodeData: Node | undefined = nodes.value.find(n => n.id === nodeId);
            const component = nodeData ? (props.nodeTypes?.[nodeData.type] ?? null) : null;
            return { nodeId, domElement, nodeData, component };
        })
        .filter((m): m is { nodeId: string; domElement: HTMLElement; nodeData: Node; component: Component } =>
            !!m.nodeData && !!m.component
        );
});

defineExpose({ engine });
</script>

<template>
  <div
    ref="containerRef"
    class="sci-flow-vue-container"
    style="width: 100%; height: 100%; position: relative; overflow: hidden;"
  >
    <!-- Vanilla engine injects SVGRenderer/CanvasRenderer here dynamically -->

    <!-- Teleport Vue Components into Vanilla DOM nodes (only when custom node type exists) -->
    <template v-for="mount in mountsArray" :key="mount.nodeId">
      <Teleport :to="mount.domElement">
        <component :is="mount.component" :node="mount.nodeData" :engine="engine" :highlighted-connection="highlightedConnection" />
      </Teleport>
    </template>

    <!-- Optional Overlays/Minimap -->
    <slot></slot>
  </div>
</template>

// packages/svelte/src/SciFlow.svelte
<script context="module" lang="ts">
  // Svelte action: moves a DOM node to a target container
  import type { Action } from "svelte/action";
  export const portal: Action<HTMLElement, HTMLElement | undefined> = (
    node,
    target,
  ) => {
    if (!target) return {};
    target.appendChild(node);
    return {
      destroy() {
        if (node.parentNode) node.parentNode.removeChild(node);
      },
    };
  };
</script>

<script lang="ts">
  import { onMount, createEventDispatcher } from "svelte";
  import {
    SciFlow,
    type SciFlowOptions,
    type Node,
    type Edge,
    type FlowState,
    type Theme,
  } from "@sci-flow/core";
  import type { ComponentType } from "svelte";

  export let initialNodes: Node[] = [];
  export let initialEdges: Edge[] = [];
  export let theme: SciFlowOptions["theme"] = "light";
  export let direction: SciFlowOptions["direction"] = "horizontal";
  export let renderer: SciFlowOptions["renderer"] = "auto";
  export let minZoom: number | undefined = undefined;
  export let maxZoom: number | undefined = undefined;
  export let nodeTypes: Record<string, ComponentType> = {};
  export let onInit: (engine: SciFlow) => void = () => {};

  const dispatch = createEventDispatcher<{
    init: SciFlow;
    change: FlowState;
  }>();
  let container: HTMLDivElement;
  let engine: SciFlow;
  let portalMounts = new Map<string, HTMLElement>();
  let highlightedConnection: FlowState["highlightedConnection"];

  onMount(() => {
    engine = new SciFlow({
      container,
      theme,
      direction,
      renderer,
      minZoom,
      maxZoom,
    });

    const stateManager = engine.stateManager;
    if (stateManager) {
      stateManager.onNodeMount = (nodeId: string, domElement: HTMLElement) => {
        portalMounts.set(nodeId, domElement);
        portalMounts = new Map(portalMounts);
      };
      stateManager.onNodeUnmount = (nodeId: string) => {
        portalMounts.delete(nodeId);
        portalMounts = new Map(portalMounts);
      };
    }

    engine.setNodes(initialNodes);
    engine.setEdges(initialEdges);

    const unsubscribe = engine.subscribe((state: FlowState) => {
      highlightedConnection = state.highlightedConnection;
      dispatch("change", state);
    });

    onInit(engine);
    dispatch("init", engine);

    return () => {
      unsubscribe();
      engine.destroy();
    };
  });

  // Reactive updates — theme and direction propagate without remounting
  $: if (
    engine &&
    initialNodes &&
    engine.getState().nodes.size !== initialNodes.length
  )
    engine.setNodes(initialNodes);
  $: if (
    engine &&
    initialEdges &&
    engine.getState().edges.size !== initialEdges.length
  )
    engine.setEdges(initialEdges);
  $: if (engine && theme !== undefined)
    engine.setTheme(theme as Partial<Theme> | "light" | "dark" | "system");
  $: if (engine && direction !== undefined) engine.setDirection(direction);

  export function fitView(padding?: number): void {
    engine?.fitView(padding);
  }
  export function centerNode(id: string): void {
    engine?.centerNode(id);
  }

  interface MountItem {
    nodeId: string;
    domElement: HTMLElement | undefined;
    nodeData: Node | undefined;
    component: ComponentType | null;
  }

  $: mountItems = Array.from(portalMounts.keys())
    .map((nodeId): MountItem => {
      const nodeData = initialNodes.find((n: Node) => n.id === nodeId);
      return {
        nodeId,
        domElement: portalMounts.get(nodeId),
        nodeData,
        component: nodeData ? (nodeTypes[nodeData.type] ?? null) : null,
      };
    })
    .filter(
      (m): m is MountItem & { nodeData: Node; component: ComponentType } =>
        !!m.nodeData && !!m.component,
    );
</script>

<div
  bind:this={container}
  class="sci-flow-svelte-container"
  style="width: 100%; height: 100%; min-height: 400px; position: relative;"
>
  {#each mountItems as mount (mount.nodeId)}
    <div use:portal={mount.domElement}>
      <svelte:component
        this={mount.component}
        node={mount.nodeData}
        {engine}
        {highlightedConnection}
      />
    </div>
  {/each}
  <slot />
</div>

<style>
  .sci-flow-svelte-container {
    overflow: hidden;
  }
</style>
