// packages/react/src/SciFlowMiniMap.tsx
import React, { useEffect, useRef } from 'react';
import { Minimap, SciFlow } from '@sci-flow/core';

export interface SciFlowMiniMapProps {
    engine: SciFlow | null;
    className?: string;
    style?: React.CSSProperties;
    width?: number;
    height?: number;
    nodeColor?: string;
    viewportColor?: string;
    backgroundColor?: string;
}

export function SciFlowMiniMap({
    engine,
    className,
    style,
    width = 150,
    height = 100,
    nodeColor,
    viewportColor,
    backgroundColor
}: SciFlowMiniMapProps) {
    const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (!containerRef.current || !engine) return;

        const stateManager = (engine as any).stateManager;
        const minimap = new Minimap({
            container: containerRef.current,
            stateManager,
            width,
            height,
            nodeColor,
            viewportColor,
            backgroundColor
        });

        return () => {
            minimap.destroy();
        };
    }, [engine, width, height, nodeColor, viewportColor, backgroundColor]);

    return (
        <div 
            ref={containerRef} 
            className={`sci-flow-minimap ${className || ''}`}
            style={{ position: 'absolute', bottom: 20, right: 20, zIndex: 100, ...style }}
        />
    );
}

// packages/vue/src/SciFlowMiniMap.vue
<template>
  <div 
    ref="containerRef" 
    class="sci-flow-minimap"
    :style="{ position: 'absolute', zIndex: 100 }"
  ></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { Minimap, SciFlow } from '@sci-flow/core';

const props = withDefaults(defineProps<{
  engine: SciFlow | null;
  width?: number;
  height?: number;
  nodeColor?: string;
  viewportColor?: string;
  backgroundColor?: string;
}>(), {
  width: 150,
  height: 100
});

const containerRef = ref<HTMLDivElement | null>(null);
let minimapInstance: Minimap | null = null;

const initMinimap = () => {
  if (minimapInstance) {
    minimapInstance.destroy();
    minimapInstance = null;
  }
  
  if (containerRef.value && props.engine) {
    const stateManager = (props.engine as any).stateManager;
    minimapInstance = new Minimap({
      container: containerRef.value,
      stateManager,
      width: props.width,
      height: props.height,
      nodeColor: props.nodeColor,
      viewportColor: props.viewportColor,
      backgroundColor: props.backgroundColor
    });
  }
};

watch(() => props.engine, initMinimap);
watch([() => props.width, () => props.height, () => props.nodeColor, () => props.viewportColor, () => props.backgroundColor], initMinimap);

onMounted(initMinimap);

onUnmounted(() => {
  if (minimapInstance) minimapInstance.destroy();
});
</script>
